version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: data_gouv_postgres
    restart: always
    environment:
      POSTGRES_USER: alexis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_gouv
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data